
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov 20 2024 02:50:37 CET (Nov 20 2024 01:50:37 UTC)

// Verification Directory fv/logical_tile_clb_mode_default__fle 

module frac_lut6_mux(in, sram, sram_inv, lut5_out, lut6_out);
  input [0:63] in;
  input [0:5] sram, sram_inv;
  output [0:1] lut5_out;
  output [0:0] lut6_out;
  wire [0:63] in;
  wire [0:5] sram, sram_inv;
  wire [0:1] lut5_out;
  wire [0:0] lut6_out;
  wire n_74, n_76, n_78, n_80, n_82, n_84, n_86, n_88;
  wire n_90, n_92, n_94, n_96, n_98, n_100, n_102, n_104;
  wire n_106, n_108, n_110, n_112, n_114, n_116, n_118, n_120;
  wire n_122, n_124, n_126, n_128, n_130, n_132, n_134, n_136;
  wire n_138, n_140, n_142, n_144, n_146, n_148, n_150, n_152;
  wire n_154, n_156, n_158, n_160, n_162, n_164, n_166, n_168;
  wire n_170, n_172, n_174, n_176, n_178, n_180, n_182, n_184;
  wire n_186, n_188, n_190, n_192;
  MX2X1 g2(.A (in[1]), .B (in[0]), .S0 (sram[0]), .Y (n_74));
  MX2X1 g4(.A (in[3]), .B (in[2]), .S0 (sram[0]), .Y (n_76));
  MX2X1 g6(.A (in[5]), .B (in[4]), .S0 (sram[0]), .Y (n_78));
  MX2X1 g8(.A (in[7]), .B (in[6]), .S0 (sram[0]), .Y (n_80));
  MX2X1 g10(.A (in[9]), .B (in[8]), .S0 (sram[0]), .Y (n_82));
  MX2X1 g12(.A (in[11]), .B (in[10]), .S0 (sram[0]), .Y (n_84));
  MX2X1 g14(.A (in[13]), .B (in[12]), .S0 (sram[0]), .Y (n_86));
  MX2X1 g16(.A (in[15]), .B (in[14]), .S0 (sram[0]), .Y (n_88));
  MX2X1 g18(.A (in[17]), .B (in[16]), .S0 (sram[0]), .Y (n_90));
  MX2X1 g20(.A (in[19]), .B (in[18]), .S0 (sram[0]), .Y (n_92));
  MX2X1 g22(.A (in[21]), .B (in[20]), .S0 (sram[0]), .Y (n_94));
  MX2X1 g24(.A (in[23]), .B (in[22]), .S0 (sram[0]), .Y (n_96));
  MX2X1 g26(.A (in[25]), .B (in[24]), .S0 (sram[0]), .Y (n_98));
  MX2X1 g28(.A (in[27]), .B (in[26]), .S0 (sram[0]), .Y (n_100));
  MX2X1 g30(.A (in[29]), .B (in[28]), .S0 (sram[0]), .Y (n_102));
  MX2X1 g32(.A (in[31]), .B (in[30]), .S0 (sram[0]), .Y (n_104));
  MX2X1 g34(.A (in[33]), .B (in[32]), .S0 (sram[0]), .Y (n_106));
  MX2X1 g36(.A (in[35]), .B (in[34]), .S0 (sram[0]), .Y (n_108));
  MX2X1 g38(.A (in[37]), .B (in[36]), .S0 (sram[0]), .Y (n_110));
  MX2X1 g40(.A (in[39]), .B (in[38]), .S0 (sram[0]), .Y (n_112));
  MX2X1 g42(.A (in[41]), .B (in[40]), .S0 (sram[0]), .Y (n_114));
  MX2X1 g44(.A (in[43]), .B (in[42]), .S0 (sram[0]), .Y (n_116));
  MX2X1 g46(.A (in[45]), .B (in[44]), .S0 (sram[0]), .Y (n_118));
  MX2X1 g48(.A (in[47]), .B (in[46]), .S0 (sram[0]), .Y (n_120));
  MX2X1 g50(.A (in[49]), .B (in[48]), .S0 (sram[0]), .Y (n_122));
  MX2X1 g52(.A (in[51]), .B (in[50]), .S0 (sram[0]), .Y (n_124));
  MX2X1 g54(.A (in[53]), .B (in[52]), .S0 (sram[0]), .Y (n_126));
  MX2X1 g56(.A (in[55]), .B (in[54]), .S0 (sram[0]), .Y (n_128));
  MX2X1 g58(.A (in[57]), .B (in[56]), .S0 (sram[0]), .Y (n_130));
  MX2X1 g60(.A (in[59]), .B (in[58]), .S0 (sram[0]), .Y (n_132));
  MX2X1 g62(.A (in[61]), .B (in[60]), .S0 (sram[0]), .Y (n_134));
  MX2X1 g64(.A (in[63]), .B (in[62]), .S0 (sram[0]), .Y (n_136));
  MX2X1 g66(.A (n_76), .B (n_74), .S0 (sram[1]), .Y (n_138));
  MX2X1 g67(.A (n_80), .B (n_78), .S0 (sram[1]), .Y (n_140));
  MX2X1 g69(.A (n_84), .B (n_82), .S0 (sram[1]), .Y (n_142));
  MX2X1 g71(.A (n_88), .B (n_86), .S0 (sram[1]), .Y (n_144));
  MX2X1 g73(.A (n_92), .B (n_90), .S0 (sram[1]), .Y (n_146));
  MX2X1 g75(.A (n_96), .B (n_94), .S0 (sram[1]), .Y (n_148));
  MX2X1 g77(.A (n_100), .B (n_98), .S0 (sram[1]), .Y (n_150));
  MX2X1 g79(.A (n_104), .B (n_102), .S0 (sram[1]), .Y (n_152));
  MX2X1 g81(.A (n_108), .B (n_106), .S0 (sram[1]), .Y (n_154));
  MX2X1 g83(.A (n_112), .B (n_110), .S0 (sram[1]), .Y (n_156));
  MX2X1 g85(.A (n_116), .B (n_114), .S0 (sram[1]), .Y (n_158));
  MX2X1 g87(.A (n_120), .B (n_118), .S0 (sram[1]), .Y (n_160));
  MX2X1 g89(.A (n_124), .B (n_122), .S0 (sram[1]), .Y (n_162));
  MX2X1 g91(.A (n_128), .B (n_126), .S0 (sram[1]), .Y (n_164));
  MX2X1 g93(.A (n_132), .B (n_130), .S0 (sram[1]), .Y (n_166));
  MX2X1 g95(.A (n_136), .B (n_134), .S0 (sram[1]), .Y (n_168));
  MX2X1 g97(.A (n_140), .B (n_138), .S0 (sram[2]), .Y (n_170));
  MX2X1 g98(.A (n_144), .B (n_142), .S0 (sram[2]), .Y (n_172));
  MX2X1 g100(.A (n_148), .B (n_146), .S0 (sram[2]), .Y (n_174));
  MX2X1 g102(.A (n_152), .B (n_150), .S0 (sram[2]), .Y (n_176));
  MX2X1 g104(.A (n_156), .B (n_154), .S0 (sram[2]), .Y (n_178));
  MX2X1 g106(.A (n_160), .B (n_158), .S0 (sram[2]), .Y (n_180));
  MX2X1 g108(.A (n_164), .B (n_162), .S0 (sram[2]), .Y (n_182));
  MX2X1 g110(.A (n_168), .B (n_166), .S0 (sram[2]), .Y (n_184));
  MX2X1 g112(.A (n_172), .B (n_170), .S0 (sram[3]), .Y (n_186));
  MX2X1 g113(.A (n_176), .B (n_174), .S0 (sram[3]), .Y (n_188));
  MX2X1 g115(.A (n_180), .B (n_178), .S0 (sram[3]), .Y (n_190));
  MX2X1 g117(.A (n_184), .B (n_182), .S0 (sram[3]), .Y (n_192));
  MX2X1 g119(.A (n_188), .B (n_186), .S0 (sram[4]), .Y (lut5_out[0]));
  MX2X1 g120(.A (n_192), .B (n_190), .S0 (sram[4]), .Y (lut5_out[1]));
  MX2X1 g121(.A (lut5_out[1]), .B (lut5_out[0]), .S0 (sram[5]), .Y
       (lut6_out));
endmodule

module frac_lut6(in, sram, sram_inv, mode, mode_inv, lut5_out,
     lut6_out);
  input [0:5] in;
  input [0:63] sram, sram_inv;
  input [0:0] mode, mode_inv;
  output [0:1] lut5_out;
  output [0:0] lut6_out;
  wire [0:5] in;
  wire [0:63] sram, sram_inv;
  wire [0:0] mode, mode_inv;
  wire [0:1] lut5_out;
  wire [0:0] lut6_out;
  wire [0:0] OR2X1_0_Y;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4;
  frac_lut6_mux frac_lut6_mux_0_(.in (sram), .sram ({in[0:4],
       OR2X1_0_Y}), .sram_inv ({UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4}), .lut5_out
       (lut5_out), .lut6_out (lut6_out));
  OR2X1 OR2X1_0_(.A (mode), .B (in[5]), .Y (OR2X1_0_Y));
endmodule

module frac_lut6_DFFRX1_mem(pReset, prog_clk, ccff_head, ccff_tail,
     mem_out, mem_outb);
  input [0:0] pReset, prog_clk, ccff_head;
  output [0:0] ccff_tail;
  output [0:64] mem_out, mem_outb;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:0] ccff_tail;
  wire [0:64] mem_out, mem_outb;
  DFFRX1 DFFRX1_0_(.RN (pReset), .CK (prog_clk), .D (ccff_head), .Q
       (mem_out[0]), .QN (mem_outb[0]));
  DFFRX1 DFFRX1_1_(.RN (pReset), .CK (prog_clk), .D (mem_out[0]), .Q
       (mem_out[1]), .QN (mem_outb[1]));
  DFFRX1 DFFRX1_2_(.RN (pReset), .CK (prog_clk), .D (mem_out[1]), .Q
       (mem_out[2]), .QN (mem_outb[2]));
  DFFRX1 DFFRX1_3_(.RN (pReset), .CK (prog_clk), .D (mem_out[2]), .Q
       (mem_out[3]), .QN (mem_outb[3]));
  DFFRX1 DFFRX1_4_(.RN (pReset), .CK (prog_clk), .D (mem_out[3]), .Q
       (mem_out[4]), .QN (mem_outb[4]));
  DFFRX1 DFFRX1_5_(.RN (pReset), .CK (prog_clk), .D (mem_out[4]), .Q
       (mem_out[5]), .QN (mem_outb[5]));
  DFFRX1 DFFRX1_6_(.RN (pReset), .CK (prog_clk), .D (mem_out[5]), .Q
       (mem_out[6]), .QN (mem_outb[6]));
  DFFRX1 DFFRX1_7_(.RN (pReset), .CK (prog_clk), .D (mem_out[6]), .Q
       (mem_out[7]), .QN (mem_outb[7]));
  DFFRX1 DFFRX1_8_(.RN (pReset), .CK (prog_clk), .D (mem_out[7]), .Q
       (mem_out[8]), .QN (mem_outb[8]));
  DFFRX1 DFFRX1_9_(.RN (pReset), .CK (prog_clk), .D (mem_out[8]), .Q
       (mem_out[9]), .QN (mem_outb[9]));
  DFFRX1 DFFRX1_10_(.RN (pReset), .CK (prog_clk), .D (mem_out[9]), .Q
       (mem_out[10]), .QN (mem_outb[10]));
  DFFRX1 DFFRX1_11_(.RN (pReset), .CK (prog_clk), .D (mem_out[10]), .Q
       (mem_out[11]), .QN (mem_outb[11]));
  DFFRX1 DFFRX1_12_(.RN (pReset), .CK (prog_clk), .D (mem_out[11]), .Q
       (mem_out[12]), .QN (mem_outb[12]));
  DFFRX1 DFFRX1_13_(.RN (pReset), .CK (prog_clk), .D (mem_out[12]), .Q
       (mem_out[13]), .QN (mem_outb[13]));
  DFFRX1 DFFRX1_14_(.RN (pReset), .CK (prog_clk), .D (mem_out[13]), .Q
       (mem_out[14]), .QN (mem_outb[14]));
  DFFRX1 DFFRX1_15_(.RN (pReset), .CK (prog_clk), .D (mem_out[14]), .Q
       (mem_out[15]), .QN (mem_outb[15]));
  DFFRX1 DFFRX1_16_(.RN (pReset), .CK (prog_clk), .D (mem_out[15]), .Q
       (mem_out[16]), .QN (mem_outb[16]));
  DFFRX1 DFFRX1_17_(.RN (pReset), .CK (prog_clk), .D (mem_out[16]), .Q
       (mem_out[17]), .QN (mem_outb[17]));
  DFFRX1 DFFRX1_18_(.RN (pReset), .CK (prog_clk), .D (mem_out[17]), .Q
       (mem_out[18]), .QN (mem_outb[18]));
  DFFRX1 DFFRX1_19_(.RN (pReset), .CK (prog_clk), .D (mem_out[18]), .Q
       (mem_out[19]), .QN (mem_outb[19]));
  DFFRX1 DFFRX1_20_(.RN (pReset), .CK (prog_clk), .D (mem_out[19]), .Q
       (mem_out[20]), .QN (mem_outb[20]));
  DFFRX1 DFFRX1_21_(.RN (pReset), .CK (prog_clk), .D (mem_out[20]), .Q
       (mem_out[21]), .QN (mem_outb[21]));
  DFFRX1 DFFRX1_22_(.RN (pReset), .CK (prog_clk), .D (mem_out[21]), .Q
       (mem_out[22]), .QN (mem_outb[22]));
  DFFRX1 DFFRX1_23_(.RN (pReset), .CK (prog_clk), .D (mem_out[22]), .Q
       (mem_out[23]), .QN (mem_outb[23]));
  DFFRX1 DFFRX1_24_(.RN (pReset), .CK (prog_clk), .D (mem_out[23]), .Q
       (mem_out[24]), .QN (mem_outb[24]));
  DFFRX1 DFFRX1_25_(.RN (pReset), .CK (prog_clk), .D (mem_out[24]), .Q
       (mem_out[25]), .QN (mem_outb[25]));
  DFFRX1 DFFRX1_26_(.RN (pReset), .CK (prog_clk), .D (mem_out[25]), .Q
       (mem_out[26]), .QN (mem_outb[26]));
  DFFRX1 DFFRX1_27_(.RN (pReset), .CK (prog_clk), .D (mem_out[26]), .Q
       (mem_out[27]), .QN (mem_outb[27]));
  DFFRX1 DFFRX1_28_(.RN (pReset), .CK (prog_clk), .D (mem_out[27]), .Q
       (mem_out[28]), .QN (mem_outb[28]));
  DFFRX1 DFFRX1_29_(.RN (pReset), .CK (prog_clk), .D (mem_out[28]), .Q
       (mem_out[29]), .QN (mem_outb[29]));
  DFFRX1 DFFRX1_30_(.RN (pReset), .CK (prog_clk), .D (mem_out[29]), .Q
       (mem_out[30]), .QN (mem_outb[30]));
  DFFRX1 DFFRX1_31_(.RN (pReset), .CK (prog_clk), .D (mem_out[30]), .Q
       (mem_out[31]), .QN (mem_outb[31]));
  DFFRX1 DFFRX1_32_(.RN (pReset), .CK (prog_clk), .D (mem_out[31]), .Q
       (mem_out[32]), .QN (mem_outb[32]));
  DFFRX1 DFFRX1_33_(.RN (pReset), .CK (prog_clk), .D (mem_out[32]), .Q
       (mem_out[33]), .QN (mem_outb[33]));
  DFFRX1 DFFRX1_34_(.RN (pReset), .CK (prog_clk), .D (mem_out[33]), .Q
       (mem_out[34]), .QN (mem_outb[34]));
  DFFRX1 DFFRX1_35_(.RN (pReset), .CK (prog_clk), .D (mem_out[34]), .Q
       (mem_out[35]), .QN (mem_outb[35]));
  DFFRX1 DFFRX1_36_(.RN (pReset), .CK (prog_clk), .D (mem_out[35]), .Q
       (mem_out[36]), .QN (mem_outb[36]));
  DFFRX1 DFFRX1_37_(.RN (pReset), .CK (prog_clk), .D (mem_out[36]), .Q
       (mem_out[37]), .QN (mem_outb[37]));
  DFFRX1 DFFRX1_38_(.RN (pReset), .CK (prog_clk), .D (mem_out[37]), .Q
       (mem_out[38]), .QN (mem_outb[38]));
  DFFRX1 DFFRX1_39_(.RN (pReset), .CK (prog_clk), .D (mem_out[38]), .Q
       (mem_out[39]), .QN (mem_outb[39]));
  DFFRX1 DFFRX1_40_(.RN (pReset), .CK (prog_clk), .D (mem_out[39]), .Q
       (mem_out[40]), .QN (mem_outb[40]));
  DFFRX1 DFFRX1_41_(.RN (pReset), .CK (prog_clk), .D (mem_out[40]), .Q
       (mem_out[41]), .QN (mem_outb[41]));
  DFFRX1 DFFRX1_42_(.RN (pReset), .CK (prog_clk), .D (mem_out[41]), .Q
       (mem_out[42]), .QN (mem_outb[42]));
  DFFRX1 DFFRX1_43_(.RN (pReset), .CK (prog_clk), .D (mem_out[42]), .Q
       (mem_out[43]), .QN (mem_outb[43]));
  DFFRX1 DFFRX1_44_(.RN (pReset), .CK (prog_clk), .D (mem_out[43]), .Q
       (mem_out[44]), .QN (mem_outb[44]));
  DFFRX1 DFFRX1_45_(.RN (pReset), .CK (prog_clk), .D (mem_out[44]), .Q
       (mem_out[45]), .QN (mem_outb[45]));
  DFFRX1 DFFRX1_46_(.RN (pReset), .CK (prog_clk), .D (mem_out[45]), .Q
       (mem_out[46]), .QN (mem_outb[46]));
  DFFRX1 DFFRX1_47_(.RN (pReset), .CK (prog_clk), .D (mem_out[46]), .Q
       (mem_out[47]), .QN (mem_outb[47]));
  DFFRX1 DFFRX1_48_(.RN (pReset), .CK (prog_clk), .D (mem_out[47]), .Q
       (mem_out[48]), .QN (mem_outb[48]));
  DFFRX1 DFFRX1_49_(.RN (pReset), .CK (prog_clk), .D (mem_out[48]), .Q
       (mem_out[49]), .QN (mem_outb[49]));
  DFFRX1 DFFRX1_50_(.RN (pReset), .CK (prog_clk), .D (mem_out[49]), .Q
       (mem_out[50]), .QN (mem_outb[50]));
  DFFRX1 DFFRX1_51_(.RN (pReset), .CK (prog_clk), .D (mem_out[50]), .Q
       (mem_out[51]), .QN (mem_outb[51]));
  DFFRX1 DFFRX1_52_(.RN (pReset), .CK (prog_clk), .D (mem_out[51]), .Q
       (mem_out[52]), .QN (mem_outb[52]));
  DFFRX1 DFFRX1_53_(.RN (pReset), .CK (prog_clk), .D (mem_out[52]), .Q
       (mem_out[53]), .QN (mem_outb[53]));
  DFFRX1 DFFRX1_54_(.RN (pReset), .CK (prog_clk), .D (mem_out[53]), .Q
       (mem_out[54]), .QN (mem_outb[54]));
  DFFRX1 DFFRX1_55_(.RN (pReset), .CK (prog_clk), .D (mem_out[54]), .Q
       (mem_out[55]), .QN (mem_outb[55]));
  DFFRX1 DFFRX1_56_(.RN (pReset), .CK (prog_clk), .D (mem_out[55]), .Q
       (mem_out[56]), .QN (mem_outb[56]));
  DFFRX1 DFFRX1_57_(.RN (pReset), .CK (prog_clk), .D (mem_out[56]), .Q
       (mem_out[57]), .QN (mem_outb[57]));
  DFFRX1 DFFRX1_58_(.RN (pReset), .CK (prog_clk), .D (mem_out[57]), .Q
       (mem_out[58]), .QN (mem_outb[58]));
  DFFRX1 DFFRX1_59_(.RN (pReset), .CK (prog_clk), .D (mem_out[58]), .Q
       (mem_out[59]), .QN (mem_outb[59]));
  DFFRX1 DFFRX1_60_(.RN (pReset), .CK (prog_clk), .D (mem_out[59]), .Q
       (mem_out[60]), .QN (mem_outb[60]));
  DFFRX1 DFFRX1_61_(.RN (pReset), .CK (prog_clk), .D (mem_out[60]), .Q
       (mem_out[61]), .QN (mem_outb[61]));
  DFFRX1 DFFRX1_62_(.RN (pReset), .CK (prog_clk), .D (mem_out[61]), .Q
       (mem_out[62]), .QN (mem_outb[62]));
  DFFRX1 DFFRX1_63_(.RN (pReset), .CK (prog_clk), .D (mem_out[62]), .Q
       (mem_out[63]), .QN (mem_outb[63]));
  DFFRX1 DFFRX1_64_(.RN (pReset), .CK (prog_clk), .D (mem_out[63]), .Q
       (ccff_tail), .QN (mem_outb[64]));
endmodule

module
     logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6(pReset,
     prog_clk, frac_lut6_in, ccff_head, frac_lut6_lut5_out,
     frac_lut6_lut6_out, ccff_tail);
  input [0:0] pReset, prog_clk, ccff_head;
  input [0:5] frac_lut6_in;
  output [0:1] frac_lut6_lut5_out;
  output [0:0] frac_lut6_lut6_out, ccff_tail;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:5] frac_lut6_in;
  wire [0:1] frac_lut6_lut5_out;
  wire [0:0] frac_lut6_lut6_out, ccff_tail;
  wire [0:63] frac_lut6_0_sram;
  wire [0:63] frac_lut6_0_sram_inv;
  wire [0:0] frac_lut6_0_mode_inv;
  wire UNCONNECTED;
  frac_lut6 frac_lut6_0_(.in (frac_lut6_in), .sram (frac_lut6_0_sram),
       .sram_inv (frac_lut6_0_sram_inv), .mode (ccff_tail), .mode_inv
       (frac_lut6_0_mode_inv), .lut5_out (frac_lut6_lut5_out),
       .lut6_out (frac_lut6_lut6_out));
  frac_lut6_DFFRX1_mem frac_lut6_DFFRX1_mem(.pReset (pReset), .prog_clk
       (prog_clk), .ccff_head (ccff_head), .ccff_tail (ccff_tail),
       .mem_out ({frac_lut6_0_sram, UNCONNECTED}), .mem_outb
       ({frac_lut6_0_sram_inv, frac_lut6_0_mode_inv}));
endmodule

module mux_tree_size2(in, sram, sram_inv, out);
  input [0:1] in, sram, sram_inv;
  output [0:0] out;
  wire [0:1] in, sram, sram_inv;
  wire [0:0] out;
  wire n_6;
  MX2X1 g3(.A (in[1]), .B (in[0]), .S0 (sram[0]), .Y (n_6));
  CLKAND2X2 g1(.A (n_6), .B (sram[1]), .Y (out));
endmodule

module mux_tree_size2_mem(pReset, prog_clk, ccff_head, ccff_tail,
     mem_out, mem_outb);
  input [0:0] pReset, prog_clk, ccff_head;
  output [0:0] ccff_tail;
  output [0:1] mem_out, mem_outb;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:0] ccff_tail;
  wire [0:1] mem_out, mem_outb;
  DFFRX1 DFFRX1_0_(.RN (pReset), .CK (prog_clk), .D (ccff_head), .Q
       (mem_out[0]), .QN (mem_outb[0]));
  DFFRX1 DFFRX1_1_(.RN (pReset), .CK (prog_clk), .D (mem_out[0]), .Q
       (ccff_tail), .QN (mem_outb[1]));
endmodule

module
     logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic(pReset,
     prog_clk, frac_logic_in, ccff_head, frac_logic_out, ccff_tail);
  input [0:0] pReset, prog_clk, ccff_head;
  input [0:5] frac_logic_in;
  output [0:1] frac_logic_out;
  output [0:0] ccff_tail;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:5] frac_logic_in;
  wire [0:1] frac_logic_out;
  wire [0:0] ccff_tail;
  wire [0:1]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut5_out;
  wire [0:0]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut6_out;
  wire [0:0]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_ccff_tail;
  wire [0:1] mux_tree_size2_0_sram;
  wire [0:1] mux_tree_size2_0_sram_inv;
  wire UNCONNECTED0;
  logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0(.pReset
       (pReset), .prog_clk (prog_clk), .frac_lut6_in (frac_logic_in),
       .ccff_head (ccff_head), .frac_lut6_lut5_out
       ({logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut5_out[0],
       frac_logic_out[1]}), .frac_lut6_lut6_out
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut6_out),
       .ccff_tail
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_ccff_tail));
  mux_tree_size2 mux_frac_logic_out_0(.in
       ({logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut6_out,
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_frac_lut6_lut5_out[0]}),
       .sram ({mux_tree_size2_0_sram[0], ccff_tail}), .sram_inv
       (mux_tree_size2_0_sram_inv), .out (frac_logic_out[0]));
  mux_tree_size2_mem mem_frac_logic_out_0(.pReset (pReset), .prog_clk
       (prog_clk), .ccff_head
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0_ccff_tail),
       .ccff_tail (ccff_tail), .mem_out ({mux_tree_size2_0_sram[0],
       UNCONNECTED0}), .mem_outb (mux_tree_size2_0_sram_inv));
endmodule

module
     logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff(set,
     reset, clk, ff_D, ff_Q, ff_clk);
  input [0:0] set, reset, clk, ff_D, ff_clk;
  output [0:0] ff_Q;
  wire [0:0] set, reset, clk, ff_D, ff_clk;
  wire [0:0] ff_Q;
  wire UNCONNECTED1;
  DFFSRX1 DFFSRX1_0_(.RN (reset), .SN (set), .CK (clk), .D (ff_D), .Q
       (ff_Q), .QN (UNCONNECTED1));
endmodule

module
     logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1(set,
     reset, clk, ff_D, ff_Q, ff_clk);
  input [0:0] set, reset, clk, ff_D, ff_clk;
  output [0:0] ff_Q;
  wire [0:0] set, reset, clk, ff_D, ff_clk;
  wire [0:0] ff_Q;
  wire UNCONNECTED2;
  DFFSRX1 DFFSRX1_0_(.RN (reset), .SN (set), .CK (clk), .D (ff_D), .Q
       (ff_Q), .QN (UNCONNECTED2));
endmodule

module mux_tree_size2_1(in, sram, sram_inv, out);
  input [0:1] in, sram, sram_inv;
  output [0:0] out;
  wire [0:1] in, sram, sram_inv;
  wire [0:0] out;
  wire n_6;
  MX2X1 g3(.A (in[1]), .B (in[0]), .S0 (sram[0]), .Y (n_6));
  CLKAND2X2 g1(.A (n_6), .B (sram[1]), .Y (out));
endmodule

module mux_tree_size2_2(in, sram, sram_inv, out);
  input [0:1] in, sram, sram_inv;
  output [0:0] out;
  wire [0:1] in, sram, sram_inv;
  wire [0:0] out;
  wire n_6;
  MX2X1 g3(.A (in[1]), .B (in[0]), .S0 (sram[0]), .Y (n_6));
  CLKAND2X2 g1(.A (n_6), .B (sram[1]), .Y (out));
endmodule

module mux_tree_size2_mem_1(pReset, prog_clk, ccff_head, ccff_tail,
     mem_out, mem_outb);
  input [0:0] pReset, prog_clk, ccff_head;
  output [0:0] ccff_tail;
  output [0:1] mem_out, mem_outb;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:0] ccff_tail;
  wire [0:1] mem_out, mem_outb;
  DFFRX1 DFFRX1_0_(.RN (pReset), .CK (prog_clk), .D (ccff_head), .Q
       (mem_out[0]), .QN (mem_outb[0]));
  DFFRX1 DFFRX1_1_(.RN (pReset), .CK (prog_clk), .D (mem_out[0]), .Q
       (ccff_tail), .QN (mem_outb[1]));
endmodule

module mux_tree_size2_mem_2(pReset, prog_clk, ccff_head, ccff_tail,
     mem_out, mem_outb);
  input [0:0] pReset, prog_clk, ccff_head;
  output [0:0] ccff_tail;
  output [0:1] mem_out, mem_outb;
  wire [0:0] pReset, prog_clk, ccff_head;
  wire [0:0] ccff_tail;
  wire [0:1] mem_out, mem_outb;
  DFFRX1 DFFRX1_0_(.RN (pReset), .CK (prog_clk), .D (ccff_head), .Q
       (mem_out[0]), .QN (mem_outb[0]));
  DFFRX1 DFFRX1_1_(.RN (pReset), .CK (prog_clk), .D (mem_out[0]), .Q
       (ccff_tail), .QN (mem_outb[1]));
endmodule

module logical_tile_clb_mode_default__fle_mode_physical__fabric(pReset,
     prog_clk, set, reset, clk, fabric_in, fabric_clk, ccff_head,
     fabric_out, ccff_tail);
  input [0:0] pReset, prog_clk, set, reset, clk, fabric_clk, ccff_head;
  input [0:5] fabric_in;
  output [0:1] fabric_out;
  output [0:0] ccff_tail;
  wire [0:0] pReset, prog_clk, set, reset, clk, fabric_clk, ccff_head;
  wire [0:5] fabric_in;
  wire [0:1] fabric_out;
  wire [0:0] ccff_tail;
  wire [0:1]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out;
  wire [0:0]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_ccff_tail;
  wire [0:0]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_0_ff_Q;
  wire [0:0]
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1_ff_Q;
  wire [0:1] mux_tree_size2_0_sram;
  wire [0:0] mux_tree_size2_mem_0_ccff_tail;
  wire [0:1] mux_tree_size2_0_sram_inv;
  wire [0:1] mux_tree_size2_1_sram;
  wire [0:1] mux_tree_size2_1_sram_inv;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z6;
  logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0(.pReset
       (pReset), .prog_clk (prog_clk), .frac_logic_in (fabric_in),
       .ccff_head (ccff_head), .frac_logic_out
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out),
       .ccff_tail
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_ccff_tail));
  logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_0(.set
       (set), .reset (reset), .clk (clk), .ff_D
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out[0]),
       .ff_Q
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_0_ff_Q),
       .ff_clk (UNCONNECTED_HIER_Z5));
  logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1(.set
       (set), .reset (reset), .clk (clk), .ff_D
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out[1]),
       .ff_Q
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1_ff_Q),
       .ff_clk (UNCONNECTED_HIER_Z6));
  mux_tree_size2_1 mux_fabric_out_0(.in
       ({logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_0_ff_Q,
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out[0]}),
       .sram ({mux_tree_size2_0_sram[0],
       mux_tree_size2_mem_0_ccff_tail}), .sram_inv
       (mux_tree_size2_0_sram_inv), .out (fabric_out[0]));
  mux_tree_size2_2 mux_fabric_out_1(.in
       ({logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff_1_ff_Q,
       logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_frac_logic_out[1]}),
       .sram ({mux_tree_size2_1_sram[0], ccff_tail}), .sram_inv
       (mux_tree_size2_1_sram_inv), .out (fabric_out[1]));
  mux_tree_size2_mem_1 mem_fabric_out_0(.pReset (pReset), .prog_clk
       (prog_clk), .ccff_head
       (logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0_ccff_tail),
       .ccff_tail (mux_tree_size2_mem_0_ccff_tail), .mem_out
       ({mux_tree_size2_0_sram[0], UNCONNECTED3}), .mem_outb
       (mux_tree_size2_0_sram_inv));
  mux_tree_size2_mem_2 mem_fabric_out_1(.pReset (pReset), .prog_clk
       (prog_clk), .ccff_head (mux_tree_size2_mem_0_ccff_tail),
       .ccff_tail (ccff_tail), .mem_out ({mux_tree_size2_1_sram[0],
       UNCONNECTED4}), .mem_outb (mux_tree_size2_1_sram_inv));
endmodule

module logical_tile_clb_mode_default__fle(pReset, prog_clk, set, reset,
     clk, fle_in, fle_clk, ccff_head, fle_out, ccff_tail);
  input [0:0] pReset, prog_clk, set, reset, clk, fle_clk, ccff_head;
  input [0:5] fle_in;
  output [0:1] fle_out;
  output [0:0] ccff_tail;
  wire [0:0] pReset, prog_clk, set, reset, clk, fle_clk, ccff_head;
  wire [0:5] fle_in;
  wire [0:1] fle_out;
  wire [0:0] ccff_tail;
  wire UNCONNECTED_HIER_Z7;
  logical_tile_clb_mode_default__fle_mode_physical__fabric
       logical_tile_clb_mode_default__fle_mode_physical__fabric_0(.pReset
       (pReset), .prog_clk (prog_clk), .set (set), .reset (reset), .clk
       (clk), .fabric_in (fle_in), .fabric_clk (UNCONNECTED_HIER_Z7),
       .ccff_head (ccff_head), .fabric_out (fle_out), .ccff_tail
       (ccff_tail));
endmodule

