
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov 18 2024 22:35:21 CET (Nov 18 2024 21:35:21 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0, tie_hi_esd;
  sky130_fd_io__top_gpio_ovtv2 gpio(.IN (Y), .INP_DIS (n_0),
       .ENABLE_INP_H (tie_hi_esd), .TIE_HI_ESD (tie_hi_esd), .VTRIP_SEL
       (1'b0), .HYS_TRIM (1'b0), .IB_MODE_SEL (2'b0), .OUT (A), .OE_N
       (DIR), .HLD_H_N (1'b1), .ENABLE_H (1'b1), .ENABLE_VDDA_H (1'b0),
       .ENABLE_VDDIO (1'b1), .ENABLE_VSWITCH_H (1'b0), .SLOW (1'b0),
       .HLD_OVR (1'b0), .ANALOG_EN (1'b0), .ANALOG_SEL (1'b0),
       .ANALOG_POL (1'b0), .DM (3'b110), .PAD (PAD));
  CLKINVX1 g3(.A (DIR), .Y (n_0));
endmodule

