
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Oct 26 2024 03:20:27 CEST (Oct 26 2024 01:20:27 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0, n_1;
  sky130_fd_sc_hd__einvp_1 g1__2398(.A (n_1), .TE (DIR), .Z (Y));
  sky130_fd_sc_hd__inv_1 g5(.A (PAD), .Y (n_1));
  sky130_fd_sc_hd__einvn_0 g2__5107(.A (n_0), .TE_B (DIR), .Z (PAD));
  sky130_fd_sc_hd__inv_1 g6(.A (A), .Y (n_0));
endmodule

