
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov 11 2024 20:42:26 CET (Nov 11 2024 19:42:26 UTC)

// Verification Directory fv/GPIO_IN 

module GPIO_IN(Y, PAD);
  output Y;
  inout PAD;
  wire Y;
  wire PAD;
  wire tie_hi_esd, tie_lo_esd;
  sky130_fd_io__top_gpio_ovtv2 gpio(.IN (Y), .INP_DIS (tie_lo_esd),
       .ENABLE_INP_H (tie_hi_esd), .TIE_HI_ESD (tie_hi_esd),
       .TIE_LO_ESD (tie_lo_esd), .VTRIP_SEL (tie_lo_esd), .HYS_TRIM
       (tie_lo_esd), .IB_MODE_SEL (2'b0), .OE_N (tie_hi_esd), .HLD_H_N
       (tie_hi_esd), .ENABLE_H (tie_hi_esd), .ENABLE_VDDA_H
       (tie_lo_esd), .ENABLE_VDDIO (tie_hi_esd), .ENABLE_VSWITCH_H
       (tie_lo_esd), .SLOW (tie_lo_esd), .HLD_OVR (tie_lo_esd),
       .ANALOG_EN (tie_lo_esd), .ANALOG_SEL (1'b0), .ANALOG_POL (1'b0),
       .DM (3'b110), .PAD (PAD));
endmodule

