
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  7 2024 12:14:43 CET (Nov  7 2024 11:14:43 UTC)

// Verification Directory fv/DFFR 

module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire n_0, n_1;
  INVxp33_ASAP7_75t_SL g4(.A (Q), .Y (QN));
  DFFASRHQNx1_ASAP7_75t_SL q_reg_reg(.SETN (n_1), .RESETN (1'b1), .CLK
       (CK), .D (n_0), .QN (Q));
  INVxp33_ASAP7_75t_SL g7(.A (RST), .Y (n_1));
  INVxp33_ASAP7_75t_SL g6(.A (D), .Y (n_0));
endmodule

