
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  7 2024 12:13:35 CET (Nov  7 2024 11:13:35 UTC)

// Verification Directory fv/DFFSRQ 

module DFFSRQ(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire n_0, n_1, n_2;
  DFFASRHQNx1_ASAP7_75t_SL q_reg_reg(.SETN (n_1), .RESETN (n_0), .CLK
       (CK), .D (n_2), .QN (Q));
  INVxp33_ASAP7_75t_SL g25(.A (D), .Y (n_2));
  INVxp33_ASAP7_75t_SL g27(.A (RST), .Y (n_1));
  INVxp33_ASAP7_75t_SL g26(.A (SET), .Y (n_0));
endmodule

