/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module DFFR(RST, CK, D, Q, QN);
  input CK;
  input D;
  output Q;
  output QN;
  input RST;
  wire q_reg;
  DFFASRHQNx1_ASAP7_75t_SL _0_ (
    .CLK(CK),
    .D(D),
    .QN(Q),
    .RESETN(1'h1),
    .SETN(RST)
  );
  assign QN = Q;
  assign q_reg = Q;
endmodule
