
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  7 2024 03:47:50 CET (Nov  7 2024 02:47:50 UTC)

// Verification Directory fv/MUX2 

module MUX2(A, B, S0, Y);
  input [0:0] A, B, S0;
  output [0:0] Y;
  wire [0:0] A, B, S0;
  wire [0:0] Y;
  wire n_0, n_1, n_2;
  NAND2xp33_ASAP7_75t_SL g30__2398(.A (n_2), .B (n_1), .Y (Y));
  NAND2xp33_ASAP7_75t_SL g31__5107(.A (n_0), .B (A), .Y (n_2));
  NAND2xp33_ASAP7_75t_SL g32__6260(.A (B), .B (S0), .Y (n_1));
  INVxp33_ASAP7_75t_SL g33(.A (S0), .Y (n_0));
endmodule

