/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux2.v:9" *)
module MUX2(A, B, S0, Y);
  (* src = "mux2.v:12" *)
  input A;
  (* src = "mux2.v:13" *)
  input B;
  (* src = "mux2.v:14" *)
  input S0;
  (* src = "mux2.v:15" *)
  output Y;
  assign Y = S0 ? B : A;
endmodule
