@echo Compile...
@echo.
@echo ex20...
@sdcc ex20.c -c --model-small
@echo fpga_lib...
@sdcc fpga_lib.c -c --model-small
@echo kb...
@sdcc kb.c -c --model-small
@echo Linking...
@sdcc ex20.rel fpga_lib.rel kb.rel --model-small
@echo.
@echo Deleting old HEx....
@echo.
@del ex20.hex
@echo.
@echo Copying IHX to HEX
@echo.
@ren ex20.ihx ex20.hex
@pause