
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  1 2025 19:09:21 CET (Feb  1 2025 18:09:21 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0, tie_hi_esd, tie_lo_esd;
  sky130_fd_io__top_gpio_ovtv2 gpio(.IN (Y), .INP_DIS (n_0),
       .ENABLE_INP_H (tie_hi_esd), .TIE_HI_ESD (tie_hi_esd),
       .TIE_LO_ESD (tie_lo_esd), .VTRIP_SEL (tie_lo_esd), .HYS_TRIM
       (tie_lo_esd), .IB_MODE_SEL (2'b0), .OUT (A), .OE_N (DIR),
       .HLD_H_N (tie_hi_esd), .ENABLE_H (tie_hi_esd), .ENABLE_VDDA_H
       (tie_lo_esd), .ENABLE_VDDIO (tie_hi_esd), .ENABLE_VSWITCH_H
       (tie_lo_esd), .SLOW (tie_lo_esd), .HLD_OVR (tie_lo_esd),
       .ANALOG_EN (tie_lo_esd), .ANALOG_SEL (1'b0), .ANALOG_POL (1'b0),
       .DM (3'b110), .PAD (PAD));
  INVX1 g3(.A (DIR), .Y (n_0));
endmodule

