-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Tue Apr 18 10:32:27 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

--  Entity Declaration

ENTITY mag_phase_accu IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		CLK : IN STD_LOGIC;
		RESET : IN STD_LOGIC;
		NEW_SAMPLE : IN STD_LOGIC;
		STEP : IN STD_LOGIC_VECTOR(7 downto 0);
		MAG : OUT STD_LOGIC_VECTOR(15 downto 0);
		PHASE : OUT STD_LOGIC_VECTOR(15 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END mag_phase_accu;


--  Architecture Body

ARCHITECTURE mag_phase_accu_architecture OF mag_phase_accu IS

SIGNAL PHASE_INT : UNSIGNED (15 DOWNTO 0);
	
BEGIN
PHASE <= STD_LOGIC_VECTOR(PHASE_INT);
--MAG <= "0100110100000000";				--	Max amplitude
MAG <= STEP&"00000000";

PHASE_PROC : PROCESS (CLK)
BEGIN
  IF (CLK'EVENT AND CLK='1') THEN
    IF (RESET='1') THEN
      PHASE_INT <=TO_UNSIGNED(0,16);
     ELSE
       IF (NEW_SAMPLE='1') THEN
         PHASE_INT <= PHASE_INT + TO_UNSIGNED (1365,16);
       END IF;
     END IF;
  END IF;
END PROCESS;

END mag_phase_accu_architecture;
