
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  2 2024 02:39:17 CET (Nov  2 2024 01:39:17 UTC)

// Verification Directory fv/fpga_top 

module fpga_top(pReset, prog_clk, set, reset, clk, gfpga_pad_GPIO_PAD,
     ccff_head, ccff_tail);
  input [0:0] pReset, prog_clk, set, reset, clk, ccff_head;
  output [0:0] ccff_tail;
  inout [0:31] gfpga_pad_GPIO_PAD;
endmodule

