-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Wed Feb 08 14:35:44 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;

--  Entity Declaration

ENTITY pulse_generator IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		clk : IN STD_LOGIC;
		slow_enable : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END pulse_generator;

-- Genrerates a pulse every 0.5 seconds

--  Architecture Body

ARCHITECTURE pulse_generator_architecture OF pulse_generator IS

signal counter : natural range 25000000 downto 0;
	
BEGIN

count : PROCESS (clk)	-- Start of process "count".
						-- outputs (counter and slow_enable) only changes when clk changes state.
  BEGIN
    IF (clk='1' and clk'event) then
      IF (counter=2499999) THEN
        counter<=0;			-- start again from the beginning
        slow_enable <= '1';	-- output must be '1'
      ELSE
        counter<=counter+1;	-- count the clockpulses
        slow_enable <= '0'; 	-- output must be '0'
      END IF;
    END IF;				-- End if positive edge on signal clk
  END PROCESS; 			-- End of process "count"

END pulse_generator_architecture;
