-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Wed Jan 25 23:25:51 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY mux_4x4_to_1x4 IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		sel : IN STD_LOGIC_VECTOR(1 downto 0);
		val1 : IN STD_LOGIC_VECTOR(3 downto 0);
		val2 : IN STD_LOGIC_VECTOR(3 downto 0);
		sum : IN STD_LOGIC_VECTOR(3 downto 0);
		dif : IN STD_LOGIC_VECTOR(3 downto 0);
		current : OUT STD_LOGIC_VECTOR(3 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END mux_4x4_to_1x4;


--  Architecture Body

ARCHITECTURE mux_4x4_to_1x4_architecture OF mux_4x4_to_1x4 IS

	
BEGIN

  current <= val1 when sel="00" else
             val2 when sel="01" else
             sum  when sel="10" else
             dif;

END mux_4x4_to_1x4_architecture;
