set_dont_touch [get_cells cb*_*__*_/mux_*_ipin_*]
set_dont_touch [get_cells sb_*__*_/mux_*_track_*]
set_dont_touch [get_cells grid_clb_1__1_/logical_tile_clb_mode_clb__0/mux_fle_*_in_*]
set_dont_touch [get_cells grid_clb_1__1_/logical_tile_clb_mode_clb__0/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_0/mux_fabric_out_*]

set_dont_touch [get_cells grid_clb_1__1_/logical_tile_clb_mode_clb__0/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_0/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut6_0/frac_lut6_0_/frac_lut6_mux_0_]

set_dont_touch [get_cells grid_clb_1__1_/logical_tile_clb_mode_clb__0/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_0/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_0/mux_frac_logic_out_0]
