
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  8 2024 18:53:50 CET (Nov  8 2024 17:53:50 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0;
  TBUFXLLVT g1__2398(.A (PAD), .OE (DIR), .Y (Y));
  TBUFX1LVT g2__5107(.A (A), .OE (n_0), .Y (PAD));
  INVXLLVT g5(.A (DIR), .Y (n_0));
endmodule

