/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "dff.v:80" *)
module DFFR(RST, CK, D, Q, QN);
  (* src = "dff.v:85" *)
  wire _0_;
  (* src = "dff.v:88" *)
  wire _1_;
  (* src = "dff.v:82" *)
  input CK;
  (* src = "dff.v:83" *)
  input D;
  (* src = "dff.v:84" *)
  output Q;
  (* src = "dff.v:85" *)
  output QN;
  (* src = "dff.v:81" *)
  input RST;
  (* src = "dff.v:88" *)
  reg q_reg;
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(_1_),
    .Y(_0_)
  );
  (* src = "dff.v:91" *)
  always @(posedge CK or posedge RST)
    if (RST)
      q_reg <= 0;
    else
      q_reg <= D;
  assign Q = q_reg;
  assign _1_ = q_reg;
  assign QN = _0_;
endmodule
