
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Oct 23 2024 03:21:52 CEST (Oct 23 2024 01:21:52 UTC)

// Verification Directory fv/DFFR 
`include "/home/ubuntu/Desktop/FPGA-OpenFPGA/Fabric/tasks/synthesizable_verilog/sky130_fd_sc_hd.v"
module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire n_0;
  sky130_fd_sc_hd__inv_1 g6(.A (RST), .Y (n_0));
  sky130_fd_sc_hd__dfrbp_1 q_reg_reg(.RESET_B (n_0), .CLK (CK), .D (D),
       .Q (Q), .Q_N (QN));
endmodule

