// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Oct 22 2024 15:48:26 CEST (Oct 22 2024 13:48:26 UTC)

// Verification Directory fv/DFFR 

module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire UNCONNECTED, n_0;
  sky130_osu_sc_18T_ms__inv_l g4(.A (QN), .Y (Q));
  sky130_osu_sc_18T_ms__dffr_1 q_reg_reg(.RN (n_0), .CK (CK), .D (D),
       .Q (UNCONNECTED), .QN (QN));
  sky130_osu_sc_18T_ms__inv_l g6(.A (RST), .Y (n_0));
endmodule
