-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Thu Jan 26 15:09:58 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY D_ff_VHDL IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		DATA : IN STD_LOGIC;
		CLK : IN STD_LOGIC;
		Q : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END D_ff_VHDL;


--  Architecture Body

ARCHITECTURE D_ff_VHDL_architecture OF D_ff_VHDL IS

	
BEGIN

D_FF_PROCESS : process (CLK) -- Output Q will only change when CLK-signal changes.
  begin
    if (clk'event and clk='1') then		-- If the clk has a rising edge (clk'event indicates that clk has just changed.
										-- clk='1' means that the new value of the clk = '1'. This is only true when a
										-- rising edge occurs at signal CLK.)
      Q <= DATA;						-- Then the output (Q) will take on the value of DATA
    end if;
  end process;

END D_ff_VHDL_architecture;
