-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Mon Jan 30 11:52:41 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY D_ff_set_reset_VHDL IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		CLK : IN STD_LOGIC;
		DATA : IN STD_LOGIC;
		RESET : IN STD_LOGIC;
		SET : IN STD_LOGIC;
		Q : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END D_ff_set_reset_VHDL;


--  Architecture Body

ARCHITECTURE D_ff_set_reset_VHDL_architecture OF D_ff_set_reset_VHDL IS

	
BEGIN

  FLIPFLOP_PROC : PROCESS (CLK,RESET,SET)
  BEGIN
    IF (RESET='1') THEN
      Q<='0';
    ELSE
      IF (SET='1') THEN
        Q<='1';
      ELSE
        IF (CLK'EVENT AND CLK='1') THEN
          Q<=DATA;
        END IF; -- POSEDGE CLK
      END IF; -- SET = '1'
    END IF; -- RESET ='1'
  END PROCESS;

END D_ff_set_reset_VHDL_architecture;
