-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Thu Jan 26 13:15:18 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY Latch_VHDL IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		CLK : IN STD_LOGIC;
		DATA : IN STD_LOGIC;
		Q : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END Latch_VHDL;


--  Architecture Body

ARCHITECTURE Latch_VHDL_architecture OF Latch_VHDL IS

	
BEGIN

LATCH_PROCESS : process (CLK, DATA)	-- each time CLK or DATA changes state, this must be evaluated
  begin
    if (clk='1') then				-- if the CLK-input is high, then
      Q <= DATA;					-- our output (Q) must be of the same value as input (DATA)
    end if; -- clk='1'
  end process; 

END Latch_VHDL_architecture;
