-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Wed Feb 08 15:55:01 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY pattern IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		clk : IN STD_LOGIC;
		ce : IN STD_LOGIC;
		LED : IN STD_LOGIC_VECTOR(6 downto 0);
		shift_out : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END pattern;


--  Architecture Body

ARCHITECTURE pattern_architecture OF pattern IS

SIGNAL temp_out : STD_LOGIC;
	
BEGIN
flipflop : PROCESS (clk)
  BEGIN
    IF (clk'event and clk='1') THEN
      IF (LED="1111111") THEN
        temp_out <= '0';
      ELSE 
        IF (LED="0000000") THEN
          temp_out<='1';
        END IF;			-- LED="0000000"
      END IF;			-- LED="1111111"
    END IF; 			-- positive edge on clk
  END PROCESS;
  shift_out <=temp_out;
END pattern_architecture;
