-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2005 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 5.1 (Build Build 176 10/26/2005)
-- Created on Sat Jan 14 22:55:14 2006

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY ex3_VHDL IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		IN1 : IN STD_LOGIC;
		IN2 : IN STD_LOGIC;
		IN3 : IN STD_LOGIC;
		IN4 : IN STD_LOGIC;
		OUT1 : OUT STD_LOGIC;
		OUT2 : OUT STD_LOGIC;
		OUT3 : OUT STD_LOGIC;
		OUT4 : OUT STD_LOGIC;
		OUT5 : OUT STD_LOGIC;
		OUT6 : OUT STD_LOGIC;
		OUT7 : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END ex3_VHDL;


--  Architecture Body

ARCHITECTURE ex3_VHDL_architecture OF ex3_VHDL IS

	
BEGIN

OUT1 <= IN1;
OUT2 <= IN2;
OUT3 <= IN1 or IN2; 					-- or function.  OUT3 <= IN1 and IN2; is also allowed.
OUT4 <= IN1 and IN2; 					-- and-function. Likewise, OUT4 <= IN1 or IN2 is also allowed.
OUT5 <= IN1 and IN2 and IN3 and IN4;
OUT6 <= IN1 or IN2 or IN3 or IN4;
OUT7 <= not(IN1 or IN2 or IN3 or IN4);


END ex3_VHDL_architecture;
