
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  2 2025 16:35:26 CET (Feb  2 2025 15:35:26 UTC)

// Verification Directory fv/GPIO_OUT 

module GPIO_OUT(A, PAD);
  input A;
  inout PAD;
  wire A;
  wire PAD;
  wire tie_hi_esd, tie_lo_esd;
  sky130_fd_io__top_gpio_ovtv2 gpio(.INP_DIS (tie_hi_esd),
       .ENABLE_INP_H (tie_hi_esd), .TIE_HI_ESD (tie_hi_esd),
       .TIE_LO_ESD (tie_lo_esd), .VTRIP_SEL (tie_lo_esd), .HYS_TRIM
       (tie_lo_esd), .IB_MODE_SEL (2'b0), .OUT (A), .OE_N (tie_lo_esd),
       .HLD_H_N (tie_hi_esd), .ENABLE_H (tie_hi_esd), .ENABLE_VDDA_H
       (tie_lo_esd), .ENABLE_VDDIO (tie_hi_esd), .ENABLE_VSWITCH_H
       (tie_lo_esd), .SLOW (tie_lo_esd), .HLD_OVR (tie_lo_esd),
       .ANALOG_EN (tie_lo_esd), .ANALOG_SEL (1'b0), .ANALOG_POL (1'b0),
       .DM (3'b110), .PAD (PAD));
endmodule

