
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jan 31 2025 19:08:31 CET (Jan 31 2025 18:08:31 UTC)

// Verification Directory fv/DFFR 

module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire n_0;
  DFFRX1 q_reg_reg(.RN (n_0), .CK (CK), .D (D), .Q (Q), .QN (QN));
  INVX1 g6(.A (RST), .Y (n_0));
endmodule

