
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jan 31 2025 18:58:35 CET (Jan 31 2025 17:58:35 UTC)

// Verification Directory fv/DFFSRQ 

module DFFSRQ(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire UNCONNECTED, n_0, n_1;
  DFFSRX1 q_reg_reg(.RN (n_0), .SN (n_1), .CK (CK), .D (D), .Q (Q), .QN
       (UNCONNECTED));
  NAND2X1 g25__2398(.A (SET), .B (n_0), .Y (n_1));
  CLKINVX1 g26(.A (RST), .Y (n_0));
endmodule

