
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb 13 2025 02:56:20 CET (Feb 13 2025 01:56:20 UTC)

// Verification Directory fv/DFFSRQ 

module DFFSRQ(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire UNCONNECTED, n_0, n_1;
  DFFSRX1 q_reg_reg(.RN (n_0), .SN (n_1), .CK (CK), .D (D), .Q (Q), .QN
       (UNCONNECTED));
  NAND2X1 g25__2398(.A (SET), .B (n_0), .Y (n_1));
  CLKINVX1 g26(.A (RST), .Y (n_0));
endmodule

