
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Nov  6 2024 21:45:39 CET (Nov  6 2024 20:45:39 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0;
  TBUFX1 g1__2398(.A (PAD), .OE (DIR), .Y (Y));
  TBUFX1 g2__5107(.A (A), .OE (n_0), .Y (PAD));
  CLKINVX1 g5(.A (DIR), .Y (n_0));
endmodule

