/* Generated by Yosys 0.45+148 (git sha1 1bf908dea, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module or2(a, b, c);
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'he >> { a, b };
endmodule
