@echo Compile...
@echo.
@echo firmware...
@sdcc firmware.c -c --model-large
@echo i2c...
@sdcc i2c.c -c --model-large
@echo lcd...
@sdcc lcd.c -c --model-large
@echo Linking...
@sdcc firmware.rel i2c.rel lcd.rel --model-large
@echo.
@echo Deleting old HEx....
@echo.
@del firmware.hex
@echo.
@echo Copying IHX to HEX
@echo.
@ren firmware.ihx firmware.hex
@pause