
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  1 2025 15:23:20 CET (Feb  1 2025 14:23:20 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_0;
  TBUFX1 g1__2398(.A (PAD), .OE (DIR), .Y (Y));
  TBUFX1 g2__5107(.A (A), .OE (n_0), .Y (PAD));
  CLKINVX1 g5(.A (DIR), .Y (n_0));
endmodule

